### ISSUE TITLE
Eucalyptus

### ISSUE THREAD

**Issue by MichelotFlorent** [Colin-Fredericks/edx-embedded-video-problems#1]
Hi,
Since the implementation of Open edX Eucalyptus, the plugin seems to have a bug. The video stops at the right time, but the pop-up question does not appear.
I suppose that the bug is related to a call dysfunction.
Thanks
F.M.

cc @sambapete

**Comment by sambapete** [comment]
I work with Florent. One of our course designers tried something.

When using the popUpProblems.js for in video questions in Eucalyptus, pop ups fail to load. To correct the problem, open popUpProblems.js and change the following lines :
214 : problemDiv = $('h3:contains(' + title + ')').parent().parent();
216 : var problemID = $('h3:contains(' + title + ')').parent().attr('id');

Reason is that questions titles in Eucalyptus are no longer in a h2 tag, but in a h3 instead. Changing h2 to h3 in the previous lines make the popups appear again.

**Comment by Colin-Fredericks** [comment]
Yes, that was exactly the issue. I thought I had fixed this (and this notification got hidden waaaay at the bottom of my list in GitHub), but I may not have fixed the zip file until today. Sorry!
